- assets/js/eggs.js
commit 39ad5ff9c50cc7bb3e6ccb3457c709871e7f3887
Author: Adem Hodzic <athos.blade@gmail.com>
Date:   Mon Dec 31 18:17:36 2018 +0100
Forgot to add ?rel=0
commit 47f9c115ee237838a2c43d0399b532d521c21376
Author: Adem Hodzic <athos.blade@gmail.com>
Date:   Mon Dec 31 18:13:52 2018 +0100
Finished my first task of updating chill easter egg
> Squashed commit of the following:

- README.md
- Added OpenSearch to list of technologies used in README file.
> Adem readme opensearch

- _includes/barnabus/link.html
- _includes/footer.html
- _includes/harley/link.html
- _includes/jorge/link.html
- _includes/karine/link.html
- about.html
- favourites.html
- flags.html
- games.html
- index.html
- movies.html
- music.html
- television.html
Removing target="_blank" rel="noopener"
fixes #67
> Change URLs to not open in a new tab

- .rubocop.yml
- README.md
- favourites.html
- games.html
- movies.html
- music.html
- television.html
Add two more links to the README in the built with section.  Target Ruby 2.5.4 now.
> Standardize liquid markup in 5 HTML files.

- assets/js/eggs.js
> Add new videos that work and remove broken ones.

- _data/favourites.csv
- favourites.html
> Redesign favourites page to fully use a CSV data file.

- _layouts/default.html
- assets/js/eggs.js
- assets/main.scss
- gallery.html
Fix fuchsia effect.
fixes #112
> Change gallery page to a grid layout.

- .circleci/config.yml
- .gitignore
- .rubocop.yml
- CODEOWNERS
- Gemfile
- Gemfile.lock
- config.toml
- scrapers/fql/upwork.fql
- scrapers/go/check-revive.sh
- scrapers/go/colly/codewars.go
- scrapers/go/colly/github.go
- scrapers/go/colly/khan.go
- scrapers/go/colly/upwork.go
- scrapers/go/ferret/upwork.go
- scrapers/php/base/common.php
- scrapers/php/khan.php
- scrapers/python/lxml/khan.py
- scrapers/ruby/nokogiri/khan.rb
- scrapers/shell/brainyquote.sh
- scrapers/shell/fuchsia-logo-downloader.sh
- scrapers/shell/github-max-per-day-awk.sh
- scrapers/shell/github-max-per-day-pcregrep.sh
- scrapers/shell/github-max-per-day-perl.sh
- scrapers/shell/github-max-per-day-ruby.sh
- scrapers/shell/github-max-per-day-sed.sh
- scrapers/shell/random-fuchsia-logo.sh
Add four more steps to the CircleCI build.  Update .rubocop.yml file with new rules.
> Add web scrapers. Update CODEOWNERS file.

- .circleci/config.yml
> Fix CircleCI Percy errors

- .circleci/config.yml
- .deepsource.toml
- .travis.yml
- assets/python/logos.py
- scrapers/python/lxml/khan.py
fixes #204 
fixes #225
fixes #231
> Add DeepSource and Travis CI config files. Fix the Pylint errors.

- assets/main.scss
- pages/games.html
> 🎮 Fix row height on the games page 🎮

- .circleci/config.yml
- .erb-lint.yml
- .hound.yml
- .overcommit.yml
- .percy.yml
- .rubocop.yml
- .travis.yml
- .yamllint
- _config.yml
- _docs/flicker-diff.md
- _docs/git.md
- lint.sh
- pages/about.html
- pages/favourites.html
- pages/flags.html
- pages/gallery.html
- pages/games.html
- pages/movies.html
- pages/music.html
- pages/parallel.html
- pages/television.html
- requirements.txt
- source/well-formed/well-formed.py
- source/xsl-schema-sort/xsl-schema-sort.xsl
Add 2 more half done scripts. Clean up HTML.
Clean up CircleCI build file.  Add Flake8
fixes #177 
fixes #222
> Add more docs.  Grid for flags page.

- .circleci/config.yml
- README.md
Update README with testing commands.
> Use sudo for npm install -g in the CircleCI config file.

- README.md
> Add Netlify status badge for logorama.

- .aspell.en.pws
- README.md
Add 3 more badges for our sites and docs to the README.
> Fix build with missing word.

- README.md
> Add and order README badges.

- README.md
Remove Logorama from Netlify.
fixes #500 for now :)
> Add links to Heroku for Logorama.

- docs/_includes/primary-nav-items.html
- docs/_sass/minima/_layout.scss
This reverts commit 74290d47fc3e0196017698c017ac587265071715.
> Revert "fixes #509 - Nav link alignment fixes (#565)"

- built-in-datatypes/built_in_datatypes.rb
- charts/run.rb
- hashcheck/hashcheck.rb
- ruby-eclipse-cheatsheets-to-dita/ruby-cheatsheets-to-dita.rb
- ruby-strip/ruby-strip.rb
- seek/seek.rb
- well-formed/well_formed.rb
> Fix Rubocop errors

- logorama/Gemfile.lock
> Fix logorama deploys by bundle install

- .github/workflows/lint.yml
- .rubocop.yml
> feat(CI): add Rubocop testing for Ruby 2.6 and 2.7

- .circleci/config.yml
- doc/source/eclipse-cheatsheets-to-dita-to-pdf.md
- doc/source/python-on-ibm-system-i.md
- doc/source/ruby-cheat-sheets.md
- doc/source/ruby.md
- doc/source/well-formed.md
- doc/source/xml.md
Add new job to CircleCI - well-formed
> Add Clays details and fix spelling and grammar

- .circleci/config.yml
- scrapers/php/github-max-per-day.php
> github-max-per-day scrapper script converted to php

- assets/cheatsheets-xml-test-data/GettingStarted/GenerateProject.xml
- assets/cheatsheets-xml-test-data/S2R/CombineTargetTracks.xml
- assets/cheatsheets-xml-test-data/S2R/GroomSensorData.xml
- assets/cheatsheets-xml-test-data/S2R/GroomingTracks.xml
- assets/cheatsheets-xml-test-data/S2R/out3.xml
- assets/cheatsheets-xml-test-data/narratives/AnalysingNarrativeData.xml
- assets/cheatsheets-xml-test-data/satc/satc_composite.xml
- assets/cheatsheets-xml-test-data/satc/single_solution.xml
Fixed misspelled all the words in "assets/cheatsheets-xml-test-data" folder.
> Some spelling fixes

- doc/source/goa.md
https://slurp.readthedocs.io/en/latest/goa.html
> goa.md: Adding title attr to image

- doc/source/harriet_the_movie.md
- doc/source/index.rst
This is the file without the author section, which we can edit anytime again, please check this out.
> harriet_the_movie.md

- Gemfile.lock
- doc/source/free-distribution-testing.md
- doc/source/parametric_statistics.md
> pre-commit fix

- docs/assets/js/spaceinvaders.js
> Fix typo in spaceinvaders.js

- README.md
> Fix the CircleCI button on the README

- .github/workflows/markdown-link-checker.yml
- .github/workflows/mlc_config.json
- README.md
- mlc_config.json
The dead links have been replaced. They are working fine now. Kindly review.
> README dead links - replaced

- .gitignore
- README.md
- doc/source/getting-started.md
- drivers/fuchsia.py
- requirements.txt
> Add Python webdriver

- docs/assets/js/eggs.js
closes #2049 
closes #2050 
refs #2047
> Fix Easter Eggs

- .deepsource.toml
> Enable more languages with DeepSource

- .circleci/config.yml
> Upgrade CircleCI to version 2.1 and use Shellcheck orb

- doc/source/sampling-methods.md
> Remove bold from heading / menu

- workers.dev/magic/wrangler.toml
- workers.dev/preston/wrangler.toml
compatibility_date = "2023-06-16"
> Fix wrangler deploys

- docs/assets/js/eggs.js
- drivers/fuchsia.py
Let's see if there are any errors now?
> Adding amir upwork to eggs js

- seek/seek.rb
> Fix seek raw CSV output format

- .readthedocs.yaml
- doc/requirements.txt
> Fix Read the Docs build

- .github/workflows/lint.yml
> actions: pre-commit skip pylint

- .pre-commit-config.yaml
https://github.com/pre-commit/pre-commit-hooks#file-contents-sorter
> pre-commit add hook file-contents-sorter for requirements.txt

- seek/seek.rb
> seek.rb: remove blank area column

- seek/seek.rb
> seek.rb: format location column

- seek/seek.rb
> run `rubocop -A`

- .github/workflows/percy.yml
> Update percy.yml - use ruby 3.3

- seek/seek.rb
> added lite version for salary 

- go.work
cc https://app.circleci.com/pipelines/github/slurpcode/slurp/9648/workflows/9cb2be66-a2af-4180-aabb-c4fbcefceeb8/jobs/77777
> Update go version from 1.21 to 1.23.0
